### ISSUE TITLE
hello-world

### ISSUE THREAD

**Issue by earthgecko** [yutongche/hello-world#2]
Hello

Users always find a way :)

A continuation of https://github.com/etsy/skyline/commit/22ae09da716267a65835472da89ac31cc5cc5192#commitcomment-16606603

@yutongche - That sounds like either Horizon was not started or redis was not available on the settings.py `REDIS_SOCKET_PATH = '/tmp/redis.sock'` socket.

It is difficult to say which as Horizon is feed here via UDP, fire and forget.

So ensure that Horizon is running.  You can do that by running the following from your command line with telnet:

```
telnet 127.0.0.1 2025

#Trying 127.0.0.1...
#Connected to 127.0.0.1.
#Escape character is '^]'.
#^]
#telnet> quit
#Connection closed.
```

That will test that you can connect to Horizon on the TCP pickle port anyway (as long as you did not change the default PICKLE_PORT in settings.py).
If Horizon is running on the TCP port, let assume for now that the UDP port will be fine as well.

Secondly ensure that redis running and is available on the socket at `REDIS_SOCKET_PATH = '/tmp/redis.sock'`.  Testing a socket is possible but if we assume that you have a default redis install it will be on port 6379.

But first, ensure that the redis config has unxisocket enabled (e.g. /etc/redis/redis.conf) with:

```
unixsocket /tmp/redis.sock
unixsocketperm 777
```

If socket was not enabled and you have enabled it in the config, restart Redis.

Test redis is available via telnet:

```
telnet 127.0.0.1 6379
```

This does not test to socket, but let us assume if the sockect is enabled and redis is running, socket is working.

If Horizon and redis are available, try run seed_data.py and we shall hope that you see...

"Congratulations! The data made it in. The Horizon pipeline seems to be working."

**Comment by earthgecko** [comment]
Sorry I used the incorrect port there 2025 will be UDP and not available via telnet so, start horizon and do

```
telnet 127.0.0.1 2024
```

By the way, you can comment on this issue here and it will notify me, there is no need to the comment on the commit message at etsy/skyline

**Comment by yutongche** [comment]
Thank you so so so much.I see the words
Congratulations! The data made it in. The Horizon pipeline seems to be working.
And could you tell me how should I use the skyline.

**Comment by earthgecko** [comment]
Have a look at the wiki pages - https://github.com/etsy/skyline/wiki

You need to send your metrics from graphite to the skyline horizon service - https://github.com/etsy/skyline/wiki/Getting-Data-Into-Skyline - describes how to add a pickle in the graphite config files and pickle all the data to skyline as well.

So graphite sends metrics to skyline horizon.  Horizon pushes the timeseries data into redis.  Analyzer pulls the metrics from redis and analyses them for anomalies against the enabled `ALGORITHMS` and sends whatever alerts you have configured for the configured metric namespace/s.

```
graphite |-> graphite carbon store
         |-> skyline horizon -> redis <- skyline analyzer -> alert
```

So for instance a simple settings.py ALERTS and SMTP_OPTS:

```
ALERTS = (
    ('stats', 'smtp', 1800),
    ('stats_counts', 'smtp', 1800),
)

# Each alert module requires additional information.
SMTP_OPTS = {
    # This specifies the sender of email alerts.
    'sender': 'skyline@<YOUR_DOMAIN.com>',
    # recipients is a dictionary mapping metric names
    # (exactly matching those listed in ALERTS) to an array of e-mail addresses
    'recipients': {
        'stats': ['you@<YOUR_DOMAIN.com>'],
        'stats_counts': ['you@<YOUR_DOMAIN.com>'],
    },
}
```

Would do the following, for any graphite metric in the namespace of stats.\* or stats_counts.\* that was detected as anomalous an alert email would be sent.

Do not expect to see anomalies or anything in the webapp immediately after starting the Skyline services.

Realistically `FULL_DURATION` should have been passed, before you begin to assess any triggered anomalies, after all `FULL_DURATION` is the baseline.  Although not all algorithms utilise
all the `FULL_DURATION` datapoints, some do and some use only 1 hour's worth.

However the Analyzer log should still report values in the exception stats, reporting how many metrics were boring, too short, etc as soon as it is getting data for metrics that Horizon is populating into redis - /var/log/skyline/analyzer.log

It takes a bit of working with to see what it can do, it is not instant :)

Good luck.

**Comment by yutongche** [comment]
@earthgecko  It seems difficult, anyway, thank you so much.

**Comment by yutongche** [comment]
@earthgecko  sorry, I have to disturb you  again. I watched a lot about skyline of the principle of web pages, but I still don't know how can I send metrics. Could you please tell me what should I do. And maybe like ' first you should do...second...' and I want to get the effect same as 'the screenshot' . And maybe you can say the method of simply. Thank you so much. :)

**Comment by earthgecko** [comment]
You have a graphite running graphing metrics?
1. See https://github.com/etsy/skyline/wiki/Getting-Data-Into-Skyline - and add your skyline IP address to the destinations in relay-rules.conf and carbon.conf as shown in the wiki page.  You will need to restart the graphite carbon services after those changes.
2. Make sure that iptables on your skyline server allows traffic from your graphite server on port 2024
3.  Graphite should now be sending data via a pickle to Horizon
4.  In your /var/log/skyline/horizon.log you should see reported queue_sizes being reported

```
tail /var/log/skyline/horizon.log
2016-03-17 18:33:36 :: 21080 :: queue size at 8
2016-03-17 18:33:36 :: 21080 :: queue size at 7
2016-03-17 18:33:36 :: 21080 :: queue size at 6
2016-03-17 18:33:36 :: 21080 :: queue size at 5
2016-03-17 18:33:36 :: 21080 :: queue size at 4
2016-03-17 18:33:36 :: 21080 :: queue size at 3
2016-03-17 18:33:36 :: 21080 :: queue size at 3
2016-03-17 18:33:36 :: 21080 :: queue size at 2
2016-03-17 18:33:36 :: 21080 :: queue size at 1
2016-03-17 18:33:36 :: 21080 :: queue size at 0
```

In your Analyzer log you should start to see metrics reported to

```
tail /var/log/skyline/analyzer.log
2016-03-17 18:34:29 :: 1116 :: seconds to run    :: 29.17
2016-03-17 18:34:29 :: 1116 :: total metrics     :: 1096
2016-03-17 18:34:29 :: 1116 :: total analyzed    :: 564
2016-03-17 18:34:29 :: 1116 :: total anomalies   :: 1
2016-03-17 18:34:29 :: 1116 :: exception stats   :: {'Boring': 527, 'Stale': 4, 'TooShort': 1}
2016-03-17 18:34:29 :: 1116 :: anomaly breakdown :: {'histogram_bins': 1, 'stddev_from_average': 1, 'stddev_from_moving_average': 1, 'first_hour_average': 1, 'median_absolute_deviation': 1, 'grubbs': 1, 'mean_subtraction_cumulation': 1}
2016-03-17 18:34:30 :: 1116 :: canary duration   :: 24.16
```

You can check the number of keys in redis with the following, see the last 2 lines that are output relating to the number of keys (=metrics):

```
redis-cli -p 6379 INFO

...
...

# Keyspace
db0:keys=1097,expires=0
```

Feel free to paste your settings.py in here or commit it as a file to this hello-world repo if you do not win.

If you do that you may as well paste your graphite relay-rules.conf and carbon.conf here too.

**Comment by yutongche** [comment]
@earthgecko 
hi, I am sorry to bother you again. This is the analyzer.log. I don't know how to change it.

started with pid 10556
/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pandas/core/ops.py:680: RuntimeWarning: invalid value encountered in less
  result = getattr(x, name)(y)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/Users/mac/Downloads/skyline/src/analyzer/analyzer.py", line 222, in run
    self.send_graphite_metric('skyline.analyzer.run_time', '%.2f' % (time() - now))
  File "/Users/mac/Downloads/skyline/src/analyzer/analyzer.py", line 50, in send_graphite_metric
    sock.connect((settings.GRAPHITE_HOST, settings.CARBON_PORT))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
gaierror: [Errno 8] nodename nor servname provided, or not known

Looking forward to your apply. Thank you very much.

**Comment by earthgecko** [comment]
Hi @yutongche 

This suggests that skyline analyzer cannot resolve the name of your graphite server e.g.

`settings.GRAPHITE_HOST, settings.CARBON_PORT`

This points at those variables from settings.py, so make sure from your skyline machine that you can telnet to:

```
telnet <settings.GRAPHITE_HOST> <settings.CARBON_PORT>
```

e.g. maybe if your hostname in `settings.GRAPHITE_HOST` was  `mactekiMBP` then:

```
telnet mactekiMBP 2003
```

Ensure that your skyline analyzer machine can nslookup

```
nslookup <settings.GRAPHITE_HOST>
```

If it is a name.

This is probably related to your /etc/hosts file or possibly your skyline machine not being able to resolve an IP address  for hostname you have specified in `settings.GRAPHITE_HOST`

Let me know if that resolves your issue.

**Comment by yutongche** [comment]
@earthgecko 
Actually, I don't know how to change it.
GRAPHITE_HOST = 'your_graphite_host.com'

**Comment by earthgecko** [comment]
Hi @yutongche 

The setting in question is in your settings.py file

```
# If you have a Graphite host set up, set this metric to get graphs on
# Skyline and Horizon. Don't include http:// since this is used for carbon host as well.
GRAPHITE_HOST = 'your_graphite_host.com'
```

You need to set that too the hostname or IP address or fully qualified domain name of the machine which you are running graphite on (which may be you local machine, I do know).

Some this is what happens.

```
graphite |-> graphite carbon store
         |-> skyline horizon -> redis <- skyline analyzer -> graphite
```

Both skyline analyzer and horizon both send metrics about themselves to graphite, they populated the skyline graphite namespace, sending metrics periodically such as the numbers of total_metrics, total_analyzed, total_anomalies, etc

If you have more problems, it would be helpful if you could add your configuration files as a a few gists - https://gist.github.com/yutongche/

Please include your:
settings.py file from skyline
carbon.conf file from graphite (and relays-rules,conf, etc if they are used)

And while you are at it a list of the packages you have installed via pip :)

A whole list is fine, from the command line:

```
pip list
```

Add it to a gist :)

**Comment by yutongche** [comment]
@earthgecko 
Sorry, I can't open the gist page. I am so stupid, I always say sorry.

And I can find the settings.py file but I don't know where are the carbon.con file and relays-rules.conf. 

I have installed  numpy, scipy, pandas, patsy, statsmodels, msgpack_python. 

I didn't fully understand your words, but I hope I guessed you mean.

**Comment by earthgecko** [comment]
Hi @yutongche 

The graphite related configuration files will be on the computer which you are running graphite on.

graphite is another application no directly related to skyline.

graphiite sends data to skyline/horizon.  If skyline gets no input data from graphite, it will not have any data to analyse.

If you have graphite installed those files will usually be in `/opt/graphite/conf/` or whatever path your graphite is installed to `<INSTALLED_PATH>/graphite/conf/`

If you do not have graphite installed search for "install graphite mac" if you want it installed on your local machine, there are a number of recipes to do that.

Also see the graphite documentation:
http://graphite.readthedocs.org/en/latest/install.html
https://github.com/graphite-project/graphite-web
https://github.com/graphite-project/carbon
https://github.com/graphite-project/whisper

**Comment by yutongche** [comment]
@earthgecko 
Thank you very much. I will learn these right now.

**Comment by earthgecko** [comment]
If you install graphite on your local machine then you are going to need to feed it with some real data.

If that is true, I recommend you install sensu (ruby) (and you may need the rabbitmq part (erlang)) on your machine as well - https://sensuapp.org/

sensu metrics your local system and sends to data to (rabbitmq ->) graphite and graphite sends to skyline.

You could also look at statsd to send data to graphite - https://github.com/etsy/statsd

There are a number of other things that can send data to graphite too - like riemann.io

Good luck :)

**Comment by yutongche** [comment]
@earthgecko 
I specially say thank you to you.I can use the skyline.
![2016-05-10 3 35 03](https://cloud.githubusercontent.com/assets/17694438/15139519/204690a0-16c9-11e6-89d6-024b04869807.png)
And I also have a little question to consult you. It is why the same data to detect abnormal, but sometimes abnormal data not come out. I know what I said is very abstract, but I don't know how to describe it more specific yet.
